language: python

sudo: false

python:
  - "2.7"

cache:
  apt: true
  directories:
  - $HOME/.cache/pip

addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - gfortran

install:
  - travis_retry pip install -r requirements.txt

script: nosetests
