language: python

python:
  - "2.7"

sudo: false

cache:
  apt: true
  directories:
  - $HOME/.cache/pip

addons:
  apt:
    packages:
    - liblapack-dev

before_install:
  - pip install -U pip setuptools wheel

install:
  - travis_retry pip install -r requirements.txt

script: nosetests
