language: python

sudo: false

python:
  - "2.7"

addons:
  apt:
    packages:
      - libblas-dev

before_install:
  - pip install -U pip setuptools wheel

install:
  - travis_retry pip install -r requirements.txt

script: nosetests
